"""
CPU core simulation module.

Orchestrates the overall processor simulation by coordinating the pipeline stages,
register file, ALU, memory subsystem, and hazard handling into a unified CPU model.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

from alu import ALU, ALUOperation
from instruction import Funct, Instruction, Mnemonic, Opcode, sign_extend_16
from memory import MemorySystem, WORD_SIZE
from registers import RegisterFile, ZERO_REGISTER


@dataclass
class ControlSignals:
    """Control lines generated by the instruction decoder."""

    reg_write: bool = False
    mem_read: bool = False
    mem_write: bool = False
    branch: bool = False
    jump: bool = False
    halt: bool = False
    alu_op: ALUOperation = ALUOperation.ADD
    write_reg: int = 0
    mem_to_reg: bool = False
    is_nop: bool = False


class InstructionDecoder:
    """Decode machine words into Instruction objects and control signals."""

    def decode_word(self, word: int) -> Tuple[Instruction, ControlSignals]:
        instr = Instruction.decode(word)
        return instr, self.control_for(instr)

    def control_for(self, instr: Instruction) -> ControlSignals:
        ctrl = ControlSignals()
        if instr.opcode == Opcode.HALT:
            ctrl.halt = True
            return ctrl
        if instr.opcode == Opcode.NOP:
            ctrl.is_nop = True
            return ctrl
        if instr.opcode == Opcode.R_TYPE:
            ctrl.reg_write = True
            ctrl.write_reg = instr.rd
            ctrl.alu_op = self._funct_to_alu(instr.funct)
            return ctrl
        if instr.opcode == Opcode.LW:
            ctrl.reg_write = True
            ctrl.mem_read = True
            ctrl.mem_to_reg = True
            ctrl.write_reg = instr.rt
            ctrl.alu_op = ALUOperation.ADD
            return ctrl
        if instr.opcode == Opcode.SW:
            ctrl.mem_write = True
            ctrl.alu_op = ALUOperation.ADD
            return ctrl
        if instr.opcode in (Opcode.BEQ, Opcode.BNE):
            ctrl.branch = True
            ctrl.alu_op = ALUOperation.SUB
            return ctrl
        if instr.opcode == Opcode.JUMP:
            ctrl.jump = True
            return ctrl
        return ctrl

    @staticmethod
    def _funct_to_alu(funct: Optional[Funct]) -> ALUOperation:
        if funct == Funct.SUB:
            return ALUOperation.SUB
        if funct == Funct.MUL:
            return ALUOperation.MUL
        return ALUOperation.ADD


class CPUCore:
    """
    Non-pipelined stage helpers and shared processor resources.

    Stage methods mirror the five pipeline phases for teaching and can be
    invoked directly for single-cycle debugging.
    """

    def __init__(self, memory: Optional[MemorySystem] = None) -> None:
        self.memory = memory or MemorySystem()
        self.pc: int = 0
        self.registers = RegisterFile()
        self.alu = ALU()
        self.decoder = InstructionDecoder()
        self.halted: bool = False

    def reset(self) -> None:
        self.pc = 0
        self.registers.reset()
        self.halted = False

    def fetch(self) -> int:
        """IF: read instruction word at PC from instruction memory."""
        return self.memory.instruction_memory.read(self.pc)

    def decode(self, word: int) -> Tuple[Instruction, ControlSignals, int, int]:
        """ID: decode word and read register operands."""
        instr, ctrl = self.decoder.decode_word(word)
        rs_val = self.registers.read(instr.rs)
        rt_val = self.registers.read(instr.rt)
        return instr, ctrl, rs_val, rt_val

    def execute(
        self,
        instr: Instruction,
        ctrl: ControlSignals,
        rs_val: int,
        rt_val: int,
        pc: int,
    ) -> Tuple[int, bool, bool, int]:
        """
        EX: ALU operation, branch resolution, effective address.

        Returns (alu_result, branch_taken, jump_taken, branch_target_pc).
        """
        branch_taken = False
        jump_taken = False
        branch_target = pc

        if ctrl.jump:
            jump_taken = True
            branch_target = (instr.immediate * WORD_SIZE) & 0xFFFFFFFF
            return 0, False, jump_taken, branch_target

        if ctrl.branch:
            diff = self.alu.execute(ctrl.alu_op, rs_val, rt_val)
            if instr.opcode == Opcode.BEQ:
                branch_taken = diff.result == 0
            elif instr.opcode == Opcode.BNE:
                branch_taken = diff.result != 0
            if branch_taken:
                branch_target = (pc + sign_extend_16(instr.immediate) * WORD_SIZE) & 0xFFFFFFFF
            return diff.result, branch_taken, False, branch_target

        if ctrl.mem_read or ctrl.mem_write:
            addr = (rs_val + sign_extend_16(instr.immediate)) & 0xFFFFFFFF
            return addr, False, False, pc

        if instr.opcode == Opcode.R_TYPE:
            result = self.alu.execute(ctrl.alu_op, rs_val, rt_val)
            return result.result, False, False, pc

        return 0, False, False, pc

    def memory_access(
        self,
        ctrl: ControlSignals,
        alu_result: int,
        rt_val: int,
    ) -> int:
        """MEM: load or store through data memory."""
        if ctrl.mem_read:
            return self.memory.data_memory.read(alu_result)
        if ctrl.mem_write:
            self.memory.data_memory.write(alu_result, rt_val)
        return alu_result

    def write_back(
        self,
        ctrl: ControlSignals,
        alu_result: int,
        mem_data: int,
    ) -> None:
        """WB: write register if enabled."""
        if ctrl.halt:
            self.halted = True
            return
        if not ctrl.reg_write or ctrl.write_reg == ZERO_REGISTER:
            return
        value = mem_data if ctrl.mem_to_reg else alu_result
        self.registers.write(ctrl.write_reg, value)

    def load_program_words(self, words: list[int]) -> int:
        return self.memory.instruction_memory.load_program(words, lock=True)
